server:
  port: 8084
spring:
  application:
    name: batchUpload-server
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB  #限制文件上传大小
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

    ##########################FastDFS文件服务配置############
#fdfs:
#  so-timeout: 1501 # 超时时间
#  connect-timeout: 601 # 连接超时时间
#  thumb-image: # 缩略图
#      width: 60
#      height: 60
#  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
#   #  - 192.168.56.101:22122